### PR TITLE
Feature- My Wishlist page

### PR DESCRIPTION
**Pull request by Koushith**
## Description

- [x] Adds my wishlist page

image

_For UI changes, include a screenshot of the changes._

### CODE REVIEW

**Review by Balakumar3018 — APPROVED** [review]
Looks good to go. 
Suggestion - you can add remove option from wish list

**Comment by Koushith** [comment]
> Looks good to go. Suggestion - you can add remove option from wish list

Thanks for the feedback. will reiterate in the UI library.

**Review by kirti2602 — APPROVED** [review]
Good to go. One small suggestion- It'd be good to add a preview link as it is what the reviewer looks for the very first time.

**Comment by Koushith** [comment]
> Good to go. One small suggestion- It'd be good to add a preview link as it is what the reviewer looks for the very first time.

Thanks for the feedback, haven't deployed yet. will do it in the next PR.

**Pull request merged**
